### ISSUE TITLE
Remove viewURI parameter from HUBContentOperationActionObserver API

### ISSUE THREAD

**Issue by krris** [spotify/HubFramework#112]
Currently API of `HUBContentOperationActionObserver` looks like this:
`- actionPerformedWithContext:viewURI:featureInfo:connectivityState:`

Since `viewURI` is a part of `HUBActionContext` we can remove it. The final API should be:
`- actionPerformedWithContext:featureInfo:connectivityState:`

**Comment by JohnSundell** [comment]
Implemented in #116
