### ISSUE TITLE
UITests are failing on Travis but reporting as a success

### ISSUE THREAD

**Issue by cerihughes** [spotify/HubFramework#127]
e.g. https://travis-ci.org/spotify/HubFramework/jobs/173907440

**Comment by cerihughes** [comment]
Also https://travis-ci.org/spotify/HubFramework/jobs/173907440#L1977

**Comment by JohnSundell** [comment]
@cerihughes Can this be closed? (since it seems like you got it working)

**Comment by JohnSundell** [comment]
This is now working 🎉
