### ISSUE TITLE
Add custom field to the component image schema

### ISSUE THREAD

**Issue by diegc** [spotify/HubFramework#134]
The component image schema should have support for custom data (type Dictionary). This enables adding per-image properties such as transformations to the images, caching policies, etc.

**Comment by JohnSundell** [comment]
There's now a custom data property on `HUBComponentImageData` (implemented in https://github.com/spotify/HubFramework/pull/157), so now we need to add support for expressing it both in JSON and using `HUBComponentImageDataBuilder`.
