### ISSUE TITLE
Move all diffing code into `HUBViewModelDiff`

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#144]
Currently, we perform diffing-like logic in `HUBViewControllerImplementation` for header & overlay components (that is, iterate over them and check if they can be reused for a new model). We should move all diffing code into `HUBViewModelDiff` instead, making it easier to find the implementation and reason about the architecture.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
