### ISSUE TITLE
Live: Reset ANSI color output after printing error message

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#163]
If the `hublive` command line interface encounters an error, it prints that error using the red ANSI color. However, it doesn't restore the original text color of the user's terminal, meaning that all subsequent messages will be of the same red error color.

Here's a screenshot reported by @josete89 in the Slack channel:
<img width="1550" alt="screen_shot_2016-11-12_at_10 31 24_am" src="https://cloud.githubusercontent.com/assets/2466701/20355622/38dba972-ac22-11e6-9588-ba045e939281.png">

We should fix this, and make sure that the terminal color is always restored after an error message is printed.

This is the code used to print with a color: https://github.com/spotify/HubFramework/blob/master/live/sources/String%2BPrintWithColor.swift

**Comment by rastersize** [comment]
Fixed with #200.
