### ISSUE TITLE
Support tvOS

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#164]
A commonly requested feature is for Hub Framework to support tvOS. Since the framework just uses standard UIKit classes, it shouldn't be too hard (famous last words 😅). It should involve the following steps:

- [ ] Enable the Hub Framework to be compiled for a tvOS target.
- [ ] Add support for the focus engine.
- [ ] Update the CI to build for tvOS as well as iOS.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
