### ISSUE TITLE
Autolayouts in components

### ISSUE THREAD

**Issue by pepibumur** [spotify/HubFramework#168]
### Context
I tried to create a component whose view has multiple subviews. These subviews are positioned using autolayouts. When the `loadView` method is called.

### Problem
If I create a view with no size in the `loadView` method and add all the subviews with the constraints, since the created root view has no size, all the defined constraints for the subviews will cause autolayouts conflicts when the component is loaded.

### Idea
- Pass the width of the `ContainerView` to the `loadView` method. That way I could create a component with that width and the preferred height.

Is there any other way to tackle the issue?
Thanks

**Comment by JohnSundell** [comment]
@pepibumur How about setting up the autolayout constraints in `configureViewWithModel:containerViewSize` (you could keep track of whether the view has been set up as to not have to do it twice). We can't send the container view size to `loadView` as its not known at that point in time.

**Comment by pepibumur** [comment]
Hi @JohnSundell 
I tried to to it at that point saving in a variable if it was setup to not do it twice but when I get that method called, I also get the height equals to 0. I fixed it by giving some size to the view when I create it in the `loadView` but don't like the approach at all because I have to hardcode a value to get the autolayouts calculation working.

**Comment by rastersize** [comment]
@pepibumur The way we do it internally is to create `UIView` subclasses that manages all of the constraints itself. Then the `HUBComponent` only instantiates the view in `-loadView`.

So given:
```objc
@interface SPTMyView: UIView
@end

@implementation SPTMyView
- (instancetype)initWithFrame:(CGRect)frame
{
     self = [super initWithFrame:frame];

     if (self) {
          UIView *subview1 = [UIView new];
          UIView *subview2 = [UIView new];

          [self addSubview:subview1];
          [self addSubview:subview1];

          NSArray<NSLayoutConstraint *> *constraints = [self createLayoutConstraints];
          [NSLayoutConstraint activateConstraints:constraints];
     }

     return self;
}

- (NSArray<NSLayoutConstraint *> *)createLayoutConstraints
{
    NSMutableArray<NSLayoutConstraint *> *constraints = [NSMutableArray new];
    // …
    return [constraints copy];
}
@end
```

We can then implement our component as:
```objc
@interface SPTMyComponent : HUBComponent
@end

@implementation SPTMyComponent
@synthesize view = _view, layoutTraits = _layoutTraits;

- (void)loadView
{
    self.view = [SPTMyView new];
}

- (void)prepareViewForReuse {}

- (void)configureViewWithModel:(id<HUBComponentModel>)model
             containerViewSize:(__unused CGSize)_
{
    SPTMyView *view = self.view;
    [self.class configureView:view withModel:model];
}

- (void)preferredViewSizeForDisplayingModel:(id<HUBComponentModel>)model
                            containerViewSize:(CGSize)containerViewSize
{
    SPTMyView *view = [SPTMyView new];
    [self.class configureView:view withModel:model];
    return [view sizeThatFits:containerViewSize]; // or something like that 😊
}

+ (void)configureView:(SPTMyView *)view withModel:(id<HUBComponentModel>)model
{
    // …
}
@end
```

---

This also has the benefit of separating concern. Letting the view deal with how things look as well as how it’s laid out. While the Hub component controls the view given events from the Hub framework. In a sense you can think of the Hub component as a light-weight view controller.

Could this approach resolve the issue for you?

**Comment by JohnSundell** [comment]
@pepibumur Happy to close this issue? 😄 Let us know if you want any additional information.

**Comment by pepibumur** [comment]
Hey @JohnSundell couldn't find time to check it out. I'll do it today.

**Comment by pepibumur** [comment]
@JohnSundell it works 😛 , thank you very much.
