### ISSUE TITLE
Make all components' (header, body + overlay) layout managed by collection view layout

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#181]
Currently, only body components are managed by a `UICollectionView` and our custom `HUBCollectionViewLayout` layout object. Header- & overlay components are laid out separately, using only the component's `preferredViewSize` as input.

We should be able to use the collection view layout to drive the layout of all components, using `z indexes` to layer the components in 3 layers (from bottom: `body, header, overlay`). This would also make it possible to use `layoutTraits` for header & overlay components.

**Comment by rastersize** [comment]
I think it might be nice to lay the (page) header as a special supplementary view with of the an element kind like `HUBPageHeaderKind`.

That way the collection view layout could more easily incorporate special logic for that component.

**Comment by JohnSundell** [comment]
@rastersize Sure, I'm all for that 👍

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
