### ISSUE TITLE
Add proper JSON parsing error reporting

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#20]
Currently it's hard to know what went wrong if a JSON file couldn't be parsed. We'll handle the error gracefully in the framework (we just ignore all invalid data) - but it would be very nice to be able to get an indication of why a certain piece of data couldn't be parsed instead of having to step through the JSON parsing code.

We already return an `NSError *` from all builders' `addJSONData:`, but that only returns an error if the JSON couldn't actually be _read_. A possible implementation would be to extend this to also be able to return some error if some data was malformed or couldn't be read.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
