### ISSUE TITLE
Enable transition between two view models

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#21]
Add an optional API to animate between two view models, so that insertions, deletions and updates can be animated. For example, if a user deletes an item that is represented by a row, that row should be able to be slided out before it gets removed from the view.

One implementation suggestion could be to enable the API user to annotate additions, updates and removals with an animation implementation. For example like this:

``` objective-c
[viewModelBuilder removeBuilderForBodyComponentModelWithIdentifier:@"row-3" withAnimation:[SPTHubAnimationSlideOutLeft new]];
```

We'll have to investage how such animations would then be performed using `UICollectionView`. I've done some experiments in the past to use `UICollectionViewTransitionLayout` to animate between two layout objects - which might be something we could use for this.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
