### ISSUE TITLE
Enable dynamic component resizing

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#22]
We'd like to enable a component to dynamically resize its view at any point in time. Currently, views are able to tell the layout system what size they would prefer to have using:

``` objective-c
- (CGSize)preferredViewSizeForDisplayingModel:(id<HUBComponentModel>)model
                            containerViewSize:(CGSize)containerViewSize;
```

However, this is only valid for when we build the `UICollectionViewLayout` during the initial rendering pass. After, if a component would resize itself, things would break. There are 2 ways we could fix this (both probably require some experimentation):

_Option 1: An explicit animation API_
- We introduce a `HUBComponentWithResizableView` protocol that components that want to support dynamic resizing can conform to.
- That new protocol gives the component a `HUBComponentResizingDelegate` (similar to how `HUBComponentWithChildren` or `HUBComponentActionPerformer` work) that it can call to initiate a resizing operation (optionally with an animation).

_Option 2: Implicit resizing_

We could probably figure out a way to observe a component's view, and when it resizes, we react to it. This would probably be harder to implement, but give component authors a lot of flexibility without having to use a specific API. With this, you could do something like:

``` objective-c
[UIView animateWithDuration:2 animations:^{
   CGRect newFrame = self.view.frame;
   newFrame.size.height = 300;
   self.view.frame = newFrame;
}];
```

**Comment by Kleemann** [comment]
This would be awesome! +1
We do a workaround today, by rescheduling the content operation when an action is performed.

Any timeline for this?

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
