### ISSUE TITLE
Add additional accessibility data for components

### ISSUE THREAD

**Issue by drphear** [spotify/HubFramework#222]
Currently there is no explicit way of handling accessibility support in components. There are of course ways to do it using customData and setting the accessibility traits and labels in the component or simply use the title of a component. 

But we should add a reserved property to the `HUBComponentModelBuilder` much like we have for logging `loggingData` to make accessibility a first class citizen in hubs. The fields that would typically be needed would be `accessibilityTraits`, `accessibilityLabel` and `accessibilityValue`.

This is useful if the first hand property fields like title and subtitle are not what is to be used for setting up the accessibility or there are components that can be used with or without e.g. title.

**Comment by JohnSundell** [comment]
Love this! 👍 

How about we make a dedicated `HUBComponentAccessibility` model (just like we have for images and targets), which would be represented as a nested dictionary `accessibility` in JSON, with the fields `traits, label & value`?

**Comment by drphear** [comment]
A dedicated model is even better, good suggestion!

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
