### ISSUE TITLE
Rename -addJSONData: and -addDataFromJSONDictionary:

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#232]
I’d like to propose a renaming of the two methods of the `HUBJSONCompatibleBuilder` protocol. The main reason is because they current import poorly in Swift.

The current methods are defined as:
```objc
- (nullable NSError *)addJSONData:(NSData *)JSONData;
- (void)addDataFromJSONDictionary:(NSDictionary<NSString *, NSObject *> *)dictionary;
```

This is problematic since the methods aren’t named consistently, which also affects Objective-C projects. As well as the name of the method dealing with a dictionary which suggests it will take some form of `NSData` from the given dictionary. Rather than adding the _contents_ of the dictionary to the view model builder.

Furthermore since the naming isn’t following Cocoa conventions the Swift importer can’t import the first method correctly. As such any usage will have to do the `let _ = …` dance.

When imported in a Swift project they look like:
```swift
public func addJSONData(_ JSONData: Data) -> Error?
public func addData(fromJSONDictionary dictionary: [String : NSObject])
```

---

As such I’d like to propose either of the two following declaration:
```objc
- (BOOL)addContentFromJSONData:(NSData *)data error:(NSError **)error NS_SWIFT_NAME(addContentFrom(jsonData:));
- (void)addContentFromJSONDictionary:(NSDictionary<NSString *, id> *)dictionary NS_SWIFT_NAME(addContentFrom(jsonDictionary:));

// Or
- (BOOL)addJSONData:(NSData *)data error:(NSError **)error NS_SWIFT_NAME(addJSON(data:));
- (void)addJSONDictionary:(NSDictionary<NSString *, id> *)dictionary NS_SWIFT_NAME(addJSON(dictionary:));
```
The first option is my personal favorite since the name states what it’s doing; adding content to the view model builder from _X_. I’ve been confused by the current name a few times already. Thinking that I had to add some JSON first before I could manipulate the view model. This naming “add content from …” also opens the API up for adding content from other sources in the future. E.g. a protobuf method could feel right at home.

Changes:
- Change to Cocoa pattern of returning a boolean and taking an out error parameter.
  - Swift translates this into its native “throws” error mechanic.
- Unites the naming so it’s coherent in both Objective-C and Swift environments.
- Changes the value type of the dictionary to `id` which will import as `Any`.
  - Otherwise the dictionary method gets _very_ annoying to use in Swift.
- Optionally; tweak the naming to make it more clear (imo).

Which would import as:
```swift
public func addContentFrom(jsonData data: Data) throws
public func addContentFrom(jsonDictionary dictionary: [String : Any])

// Or
public func addJSON(data: Data) throws
public func addJSON(dictionary: [String : Any])
```

Thoughts @JohnSundell?

---

If “aye” I’ll implement the changes.

**Comment by JohnSundell** [comment]
I say "aye" to the second option 😄

```objective-c
- (BOOL)addJSONData:(NSData *)data error:(NSError **)error NS_SWIFT_NAME(addJSON(data:));
- (void)addJSONDictionary:(NSDictionary<NSString *, id> *)dictionary NS_SWIFT_NAME(addJSON(dictionary:));
```
