### ISSUE TITLE
Add a discussion in the readme comparing this to other overlapping libraries (AsyncDisplayKit, ComponentKit, etc.)

### ISSUE THREAD

**Issue by michaeleiselsc** [spotify/HubFramework#247]
There are some popular libraries out there that overlap with this library. Moving between them would take a lot of time, so it's important to pick the correct library for one's needs the first time. Adding a comparison would make it much easier for people to understand the tradeoffs and, assuming Hub has good tradeoffs, increase adoption of the library.

**Comment by rastersize** [comment]
@michaeleiselsc Thanks for the suggestion. We’ll see what can be done about it.

---

In the meantime here’s a _quick_ summary of the differences with the libraries you mention. For you (if your still wondering) and for future reference.
- Hub Framework is a tool for taking some content, e.g. from JSON, and rendering it in a collection view. Showing said content using your own components (i.e. views).
  - There’s a lot more which is covered in the [Getting started](https://spotify.github.io/HubFramework/getting-started-guide.html) and [concepts](https://spotify.github.io/HubFramework/concept-guide.html) guides.
- AsyncDisplayKit lets you move image decoding, text sizing and rendering, layout, and other expensive UI operations off the main thread, to keep the main thread available to respond to user interaction.
  - As such it’s something that could, theoretically, be used by Hub Framework to speed up rendering.
- ComponentKit is similar to Hub Framework in that it’s great for showing “list views”. I’ve not used it myself but from I can tell one difference is that Hub Framework is tailored to “[backend driven UIs](https://spotify.github.io/HubFramework/concept-guide.html#backend-driven-uis)”.
  - That is an entire view can be completely changed in the client by changing the JSON returned by your backend endpoint. AFAIK this would require code changes, or duplication of Hub Framework functionality in your app, with ComponentKit.
  - ComponentKit requires you to use Objective-C++ which unfortunately means it cannot be used from a Swift app.
  - ComponentKit borrows much from React which obviously makes it very interesting 😸

**Comment by michaeleiselsc** [comment]
Thanks for the summary! Right now, the company I work for will probably pick AsyncDisplayKit because it solves immediate performance needs, and then see if Hub can be integrated later. I'll check back in on the project and its integration. But I think it will help adoption to make them work together, especially if it somehow provided a layer over AsyncDisplayKit so you didn't have to dig too deeply into AsyncDisplayKit to get started

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
