### ISSUE TITLE
Unify parameters passed to content operations

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#252]
In the PR “Introduce HUBBlockContentOperation + context” (#199) @JohnSundell introduced the `HUBContentOperationContext` protocol which encapsulates all values passed to a content operation. However the PR only made it available to the block based content operation. The intention is to pass an object of this type to all content operations. Instead of sending the values as individual parameters.

The main reason we want to move to a context object over individual parameters is due to scalability. Continuing to add parameters to the `performWith…` method will quickly make it hard to work with and maintain. We also want to keep the way API consumers write content operations the coherent between “normal” (custom class) operation and block based operations.

Furthermore the `HUBContentOperationWithPaginatedContent` protocol declares an almost identical, but still different, method. Which requires us to keep its `append` method parameters in sync.

## Proposal
I propose that we refactor the `perform` method of `HUBContentOperation` and the `append` method of `HUBContentOperationWithPaginatedContent` to using a context parameter. Instead of their existing parameters. This change would be an API breaking change. However it will insulate us such that we can make future changes to the API of what a content operation is provided.

API wise the change would be like follows.

### `HUBContentOperation`
```objc
@protocol HUBContentOperation <NSObject>
// Before
- (void)performForViewURI:(NSURL *)viewURI
              featureInfo:(id<HUBFeatureInfo>)featureInfo
        connectivityState:(HUBConnectivityState)connectivityState
         viewModelBuilder:(id<HUBViewModelBuilder>)viewModelBuilder
            previousError:(nullable NSError *)previousError;

// After
- (void)performInContext:(id<HUBContentOperationContext>)context;
@end
```
```swift
// Imports in Swift as
func perform(in context: HUBContentOperationContext)
```

The consumer side the change results in that existing code will need to prepend any use of `viewURI`, 
`featureInfo`, `connectivityState`, `viewModelBuilder` and `previousError` with `context.`. Obviously after changing the method definition 😉

### `HUBContentOperationWithPaginatedContent`
```objc
@protocol HUBContentOperationWithPaginatedContent <NSObject>
// Before
- (void)appendContentForPageIndex:(NSUInteger)pageIndex
               toViewModelBuilder:(id<HUBViewModelBuilder>)viewModelBuilder
                          viewURI:(NSURL *)viewURI
                      featureInfo:(id<HUBFeatureInfo>)featureInfo
                connectivityState:(HUBConnectivityState)connectivityState
                    previousError:(nullable NSError *)previousError NS_SWIFT_NAME(appendContent(pageIndex:viewModelBuilder:viewURI:featureInfo:connectivityState:previousError:));

// After
- (void)appendContentForPageIndex:(NSUInteger)pageIndex
                        inContext:(id<HUBContentOperationContext>)context NS_SWIFT_NAME(appendContent(atPageIndex:in:));
@end
```
```swift
// Imports in Swift as
func appendContent(atPageIndex pageIndex: UInt, in context: HUBContentOperationContext)
```

## Alternatives
Keep adding parameters to the `performForViewURI:…` and `appendContentForPageIndex:…` methods.

However it’s my firm belief this is an anti-pattern. It will lead to more API breakage and maintenance pains.

## Not considered
- Moving `pageIndex` to `HUBContentOperationContext` as to unify the two protocols even.

#### `HUBContentOperationContext`
The existing `HUBContentOperationContext` type looks like:
```objc
NS_ASSUME_NONNULL_BEGIN

/**
 *  Protocol defining the public API of a content operation context
 *
 *  This API is currently only used with `HUBBlockContentOperation`. For more information
 *  about the properties that are part of this API, refer to `HUBContentOperation`, or to
 *  the "Content programming guide".
 */
@protocol HUBContentOperationContext <NSObject>

/// The URI of the view that the content operation is being used in
@property (nonatomic, copy, readonly) NSURL *viewURI;

/// An object containing information about the feature that the operation is being used in
@property (nonatomic, strong, readonly) id<HUBFeatureInfo> featureInfo;

/// The current connectivity state, as resolved by `HUBConnectivityStateResolver`
@property (nonatomic, assign, readonly) HUBConnectivityState connectivityState;

/// The builder that can be used to add, change or remove content to/from the view
@property (nonatomic, strong, readonly) id<HUBViewModelBuilder> viewModelBuilder;

/// Any error encountered by a previous content operation in the view's content loading chain
@property (nonatomic, strong, readonly, nullable) NSError *previousError;

@end

NS_ASSUME_NONNULL_END
```

**Comment by dalef84** [comment]
I like this. I haven't used Hubs extensively yet but I agree with the scalability argument of this RFC. I'd love to see more of this in the rest of the framework too.

Just my 50 cents. 👍

**Comment by krris** [comment]
Totally agree. Good idea 👍

**Comment by rastersize** [comment]
We’ve also spoken about this internally and has come to agreement.

RFC has been approved ✅
