### ISSUE TITLE
testCollectionViewContentInsetEqualToHeaderHeight fails, sometimes

### ISSUE THREAD

**Issue by marmelroy** [spotify/HubFramework#264]
It appears like the following UI test fails, sometimes. Here's the error message on Travis:
```
HubFrameworkDemoUITests.HeaderComponentUITests
testCollectionViewContentInsetEqualToHeaderHeight, XCTAssertEqual failed: ("64.0") is not equal to ("250.0").
```

I was unable to reproduce this failure locally.

This bug affected:
https://github.com/spotify/HubFramework/pull/257
https://github.com/spotify/HubFramework/pull/263 (fixed by relaunching Travis)

**Comment by marmelroy** [comment]
Possibly fixed by https://github.com/spotify/HubFramework/pull/263/commits/095010749e35fdde0dd0bf7602e8e6e29e2285fc.

Testing whether the content inset is actually equal to the header height instead of a hardcoded value.

**Comment by cerihughes** [comment]
Thanks for the info @marmelroy 

I've been seeing this problem for a while now, although the reports I get back from Travis don't seem to show any tests failing. I just get a failed build every time for https://github.com/spotify/HubFramework/pull/257

Is this your experience too?

**Comment by marmelroy** [comment]
Hey @cerihughes! Thanks but it seems like your PR is dealing with a different issue. Your build fails because of a Danger rule (and Fastlane seems to be capturing the log so you don't see the exact reason in the Travis output).
 
I had a quick look and it seems very likely that it's failing because your PR body is empty. Danger wants it to have at least 5 characters. Try adding a PR description. 

p.s. Joining next week! Can't wait. 🎉

**Comment by cerihughes** [comment]
Aha! Thanks @marmelroy. Didn't think of the empty PR description. See you in Stockholm next week!

**Comment by rastersize** [comment]
Marked this as a `severe` issue given that it happens quite often and affects developer productivity.

---

@marmelroy Super happy to hear you’re joining us! 😃

**Comment by cerihughes** [comment]
Fixed as part of https://github.com/spotify/HubFramework/pull/269
