### ISSUE TITLE
RFC: Styling the root Hub Framework view

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#271]
Many apps needs to be able to style the Hub Framework’s (HF’s) root view (i.e. currently the collection view). The most common is to set a background color or other similar customizations. As it’s not possible to subclass `HUBViewController` today users of the framework are left with two possible workarounds.

These workaround are to to either front-load the view or wrap `HUBViewController` with a parent. Both are bad, for different reasons. The first workaround is bad since it breaks the life cycle of the view and might result in performance issues. The second option is also bad since it requires hacking with the view hierarchy. Forcing user’s of HF to make assumptions as to where in the hierarchy the root HF view is supposed to be. One cannot even look for a specific type since that is unknown or might even be, just, `UIView`.

The second workaround also suffers from low code-reuse. Since each implementing app needs to duplicate this.

## Proposal
As such I propose we implement one of two solutions.
- Make `HUBViewController` subclass-able.
- Add a “styler” property which takes a block.

Both of which solves the issues laid out above.

### Proposal A: Subclassing
Currently `HUBViewController` does not support subclassing since the designated initializer isn’t part of the public API. This change would involve moving the current from the private header to the public.

Our use case here is basically the use-case that subclassing was designed for, IMO 😄

#### Advantages
- Clear, standardized way of customizing the view controller as needed.
- Supports much deeper customization if needed at any point in the life cycle.
- Allows the user of the framework to decide when a new style needs to be applied.
  - For example in the case of a theming system that goes from _Theme A_ 👉 _Theme B_.

#### Disadvantages
- The initializer is massive
  - Although this might help in looking into refactoring it as well as `HUBViewController`.
- Less clear on how to create a Hub view.
  - The view controller shouldn’t be instantiated by users of the framework. Instead one should get an instance from the factory.
- Subclasses and their unintended affects and effects when the class isn’t fully designed to be subclassed.
- Still requires a custom wrapping view controller factory.

### Proposal B: Styler
We add a property which takes a block that styles the root view and is ran at appropriate times. Appropriate times might be during `-viewDidLoad` and when dynamic type changes occur.

<details><summary>Example implementation</summary>

**HUBViewController.h**
```objc
typedef void (^HUBViewStyler)(UIView *view);

@interface HUBViewController : UIViewController <...>
// ...

/// A block that styles the view controller’s view.
@property (nonatomic, copy, nullable) HUBViewStyler viewStyler;
@end
```

**HUBViewController.m**
```objc
@implementation HUBViewController
- (void)viewDidLoad
{
    [super viewDidLoad];

    // ...

    [self applyViewStyle];    
}

- (void)handleDynamicTypeChangeNotification:(NSNotification *)changeNotification
{
    [self applyViewStyle];
}

- (void)applyViewStyle
{
    HUBViewStyler viewStyler = self.viewStyler;
    if (viewStyler) {
        self.viewStyler(self.view);
    }
}
@end
```
</details>

#### Advantages
- We don’t have to take into account subclass-ability when making changes to `HUBViewController`.
- Clear expectation on what should be styled while we control when it happens.

#### Disadvantages
- The user would only be able to style the view we pass in to the block.
- The user wouldn’t be able to handle other events and edge cases.
- There might be more situations where the style should be re-applied. We wouldn’t be able to support that in this case.
  - For example in the case of a theming system that goes from _Theme A_ 👉 _Theme B_.

## Not considered
- Allowing users of the framework to inject the root view that should be used.
  - This might be something we want anyhow in the future. To support more advanced use cases.

**Comment by marmelroy** [comment]
This is a super interesting topic. 

My thoughts:
- I generally try and make most classes final as subclassability introduces a fair amount of fragility into a framework.

- That said, I am in favour of proposal A. We are asking users of Hub to trust the framework with a significant portion of their UI and we should do our best to support "deep" customisation. The main issue with proposal B is that it requires us to make too many assumptions about what kind of customisation users are after and when to apply it.

- We can and we should, however, mitigate some of the damages of subclassability by offloading critical responsibilities from the HUBViewController to other non-subclassable classes. It's currently responsible for a lot...

**Comment by mhallendal** [comment]
@rastersize for this specific case I'm not sure I follow the problem of simply setting the `hubViewController.view.backgroundColor` similar to how it's done in the demo application.

https://github.com/spotify/HubFramework/blob/master/demo/sources/AppDelegate.swift#L206

**Comment by rastersize** [comment]
@mhallendal That might be fine for a demo app. However it has the side-effect of loading the view before it’s supposed to, or even needs to, be loaded. Which is undesirable.

Furthermore it ties the styling of the view to the part of the app which deals with navigation. Which would break the separation of concern.

**Comment by mhallendal** [comment]
Ah, that's what you meant about front load the view above. I'm unsure what the problem with doing that would be but I agree about the page loading mechanism shouldn't be concerned with it. However the page loading mechanism in your app could delegate that elsewhere.

Not optimal but option A sounds like a pretty invasive change that we would prefer not to do now and option B adds even more concepts to the framework.

That said, I haven't looked into enough what it would mean to make HubsViewController subclassable. For now it's probably easiest to just do something similar to what the demo app does (or embed it in another view that sets the background color).

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
