### ISSUE TITLE
Passing arguments to a feature

### ISSUE THREAD

**Issue by pabloelizalde** [spotify/HubFramework#293]
I am a newbie in the HubFramwork, and I having some issues passing arguments to my features.
I have a feature that I registered with an URI 

`myscheme://productDetail`.

But my idea is to call this feature with an URI like 

`myscheme://productDetail/{product_id}`

 Then get the `product_id` argument, and in the HUBContentOperation make a request to get the json data for that specific product.
Is there a way that I can do that? What is the best way for passing arguments to the HUBContentOperation?

**Comment by foreldet** [comment]
Could you find a solution? Thanks!

**Comment by pabloelizalde** [comment]
Hi @foreldet , I managed to make it work.
I included my `productId` as a `URLComponent` to the URI. And then in my `HUBContentOperation` where `viewURI` is an argument in the `perform` method I access to the productId like `viewURI.path`.

**Comment by foreldet** [comment]
Thanks! It's working now :-)

If someone else gets stuck with the same, it is useful to know that when registering a feature you can use a "predicateWithRootViewURI" instead of "predicateWithViewURI" to accept the given URI.
