### ISSUE TITLE
How to access ViewController's lifecycle events?

### ISSUE THREAD

**Issue by CalvHobbes** [spotify/HubFramework#295]
Is there a way to listen in on the ViewController's lifecycle events (ViewWillAppear, ViewDidLoad/Unload etc.) in a HubContentOperation and in a HubComponent? I know theres's a protocol called HUBComponentViewObserver but that only provides the viewwillappear and resize events.

**Comment by mhallendal** [comment]
Not as far as I know.

Components can be notified when that component will be shown (which may or may not be at the same time the view controller gets shown). Content Operations aren't really meant to care about that (afaik).

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
