### ISSUE TITLE
Add lane for releasing a new version

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#30]
To simply the creation of a new release it’d be nice to have a fastlane lane doing the boring bits.
### Requirements

It should…
- [ ] take a single argument ala. `fastlane release version:2.1.0`.
- [ ] update `module_version` in `.jazzy.yml`.
- [ ] update `s.version` in `HubFramework.podspec`.
- [ ] generate a changelog for the release.
  - Should follow the standard changelog format. _[TODO(@rastersize): Find link to the standard.]_
  - Should be useable for a CHANGELOG.md file as well as the GitHub release notes.
- [ ] commit all of its changes with the a message like: `Bumping framework version to X.Y.Z`
- [ ] tag the newly version bump commit as `X.Y.Z` (e.g. `2.1.0`).
- [ ] optionally push the commit and tag to GitHub (controlled by an argument ala. `push:<true|false>`).
  - Should default to `true`.

Stretch goal: have the lane turn the git tag to a GitHub release automatically and set the release notes to the generated changelog.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
