### ISSUE TITLE
Switch to semantic versioning

### ISSUE THREAD

**Issue by mhallendal** [spotify/HubFramework#305]
Starting with version 3.0.0 we intend to switch over to Semantic Versioning. Meaning that the version will encode information about API changes. 

In practice this means that the version number is divided into three parts major.minor.micro. Any API breaking changes requires a bump of the major part, an API addition bumps the minor part and any fixes bump the micro part.

A 2.x branch will be created for any critical fix on the current version. Development towards 3.x will happen on the master branch.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
