### ISSUE TITLE
HTML Content

### ISSUE THREAD

**Issue by clozinski** [spotify/HubFramework#311]
First thank you for the brilliant piece of work.  Quite inspirational.  

It is great to get something for free.  Of course I want more!

I run iosLinks.info, the world’s largest iOS directory.  I want to port it to Hub Framework.  Generally it looks quite easy to do.   Each of my content objects has its own URL, and  a display class where I can create the appropriate json template, and display it as a view on that URL.  Great so far. 

The biggest problem is that I have lots of HTML content.  So I would have to create an HTML content object.  Some subclass of UIWebView.  Not that hard to do, but of course it would be lot lot easier if someone had already made one.  

Are there any out there?  Can an existing row display HTML content?

Thanks for all the great work. 
Christopher Lozinski

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
