### ISSUE TITLE
Have one way to observe contentOffset

### ISSUE THREAD

**Issue by marmelroy** [spotify/HubFramework#312]
Currently, we report changes in contentOffset **internally** to hub components by enumerating them in scrollViewDidScroll and calling a method from HUBComponentContentOffsetObserver. 

We have no solution for reporting contentOffset changes **externally** but we do have a scrollHandler that lets Hubs users modify things like contentInset and observe scrollingDidStart and didEnd events. 

To be able to observe contentOffset changes externally, I added a new didScroll method to the scrollHandler in: https://github.com/spotify/HubFramework/pull/310

There's no good reason to have two ways of observing contentOffset changes. 

The correct approach in my opinion is to have a ScrollHandlerObserver protocol and allow any class with access to the scrollHandler to register/unregister itself as an observer. That way it could optionally implement didStart/didScroll/didEnd events and we will have one clean solution for external and internal observation.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
