### ISSUE TITLE
License-linter currently requires Copyright 2016

### ISSUE THREAD

**Issue by mhallendal** [spotify/HubFramework#319]
There is a linter to verify that all files have the license header. However this linter is hard coded to Copyright 2016 and fails as soon as a file copyright "2017" or "2016-2017" is committed.

The template lives in [license_header_template.txt ](https://github.com/spotify/HubFramework/blob/master/other/license_header_template.txt) and the script is [lint_license_conformance](https://github.com/spotify/HubFramework/blob/master/fastlane/scripts/lint_license_conformance).

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
