### ISSUE TITLE
New CocoaPods version release

### ISSUE THREAD

**Issue by jewilhel** [spotify/HubFramework#321]
Please release new and latest cocoaPod version. Was having trouble with NSObject inheritance. This inheritance has already been removed, apparently and just needs to be made available.

Thanks -  Jason W.

**Comment by fusionbeam** [comment]
Same here.

**Comment by jewilhel** [comment]
Encountered other apparent bugs that might be fixed with a new release!

**Comment by ynmehel** [comment]
Version `2.0.10` has been released
