### ISSUE TITLE
Add Danger rule verifying test and mock files are only in the tests target 

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#34]
It should
- verify that all files matching `.*Tests.[hm]$` are only in the HubFrameworkTests target.
- verify that all files matching `.*Mock.[hm]$` are only in the HubFrameworkTests target.
- verify that no files in the HubFramework target are in the HubFrameworkTests target, and vice-verse.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
