### ISSUE TITLE
Not possible to use HubFramework in framework project

### ISSUE THREAD

**Issue by iheart2code** [spotify/HubFramework#344]
I am trying to extend an application that uses HubFramework for the UI layer. I have created my own framework project to keep my code separate from the main application. Unfortunately, when I try to add HubFramework to my framework via CocoaPods & build, I get a compiler error.

> `'sharedApplication' is unavailable: not available on iOS (App Extension) - use view controller based solutions where appropriate instead.`

I would like the ability to define components, actions, etc in a separate framework Xcode project and make use of those components in a separate application Xcode project.

It appears that AFNetworking has an [interesting way of solving this issue](https://github.com/AFNetworking/AFNetworking/issues/2119). It would be nice if HubFramework could adapt a similar solution for supporting framework projects.

**Comment by iheart2code** [comment]
I was able to work around this issue with the following snippet applied to the bottom of my Podfile. This is likely not an ideal solution for all use cases, but it works for me.

```ruby
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == 'HubFramework'
            target.build_configurations.each do |config|
                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            end
        end
    end
end
```

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
