### ISSUE TITLE
Weird selection behavior

### ISSUE THREAD

**Issue by foreldet** [spotify/HubFramework#345]
I've been trying to implement item selection in a list as it's done in the HubFrameworkDemo, but I found that in the "Pretty Pictures" example, the first list within a carousel has a weird behavior when the first item is selected.

After pressing it for the first time, everything works as expected, but after pressing "Done" button the item remains selected until you do a long press over it.

As a workaround, I could make it work as expected by changing a line in HUBViewControllerImplementation.m:

`[self selectComponentWithModel:componentWrapper.model customData:nil];`

to
`dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                [componentWrapper updateViewForSelectionState:HUBComponentSelectionStateNone];
            });`

Probably there is a more elegant way to fix it and I haven't studied the framework enough to be aware of what the previous line was supposed to do, but I hope it can help to find a proper fix.

Edit: I've seen that my change makes the first list in HubFrameworkDemo to stop working, so I guess it's something else missing there. It works as expected if the replacing lines are inserted after `[self selectComponentWithModel:componentWrapper.model customData:nil];` instead of replacing it.

Edit 2: One alternative would be to add 'self.cancelTouchesInView = NO;" to 'HUBComponentGestureRecognizer.m'. By doing that, it could be possible to customise touch events and not have them automatically rejected by the framework, which can be useful in multiple cases, like custom UIControls or interactive views.

**Comment by mindgraffiti** [comment]
I am experiencing the same problem.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
