### ISSUE TITLE
CollectionView Shifted down in iOS 11

### ISSUE THREAD

**Issue by mattcee** [spotify/HubFramework#346]
Collection view is shifted when a header is not included in iOS 11 Beta. It also happens in the demo app where all the content is shifted down around 50 pixels?

setting automatically manage top content inset fixes the issue

`    func viewControllerShouldAutomaticallyManageTopContentInset(_ viewController: HUBViewController) -> Bool {
        return false
    }`

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
