### ISSUE TITLE
Add workaround for “Error 65” on CI

### ISSUE THREAD

**Issue by rastersize** [spotify/HubFramework#43]
We consistently keep getting “Error 65” on CI. It seems like it’s the simulator timing out or in other ways stops responding.

**Comment by JohnSundell** [comment]
@jklausa suggested to me on Twitter that using Xcode 8.2 has helped their team avoid this issue. Maybe we can try running only our UI tests on Xcode 8.2 and see if it helps?

**Comment by JohnSundell** [comment]
Bumping to Xcode 8.1 seem to have helped a lot (fingers crossed). Let's keep track of it for a week or so, and hopefully we can close this ticket.

**Comment by rastersize** [comment]
In Xcode 8.2 Apple is supposed to have [re-worked how the simulator is launched](https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-261757936). Making things better.

However it seems to be a problem of CPU congestion. Which is very common when running on virtual machines, which is an issue that’ll persists even when upgraded to 8.2. We’ve been in contact with other companies that run on dedicated hardware instead and they haven’t experienced “error 65” at all (more or less). One workaround, [suggested by an Apple iOS simulator engineer](https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-261806496), for the issue seems to be wait for 30-60 seconds. We’re currently waiting for around 10 seconds so might bump that.

**Comment by dflems** [comment]
Still lots of [problems](https://twitter.com/steipete/status/809485058671341569) with 8.2 unfortunately :cry:

Different problems, but problems nonetheless.

**Comment by jklausa** [comment]
Just to add my two cents, again: I haven't looked closely at our CI in a while (heads down on a different project), but I've heard even with 8.2 it's gotten somewhat worse over last weeks. 

Pet theory is that the improvement we've seen in 8.2 can be chalked up to the VMs being spun on a different set of HW, where we didn't have as many other projects to contend with — so things were just slightly faster, but slightly faster _enough_ :( 

(we're using bitrise, fwiw)

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
