### ISSUE TITLE
Image loader: Replace cache-check with timer

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#51]
Currently, we ask each implementation of `HUBImageLoader` to return whether an image was loaded from cache or not. This parameter is in turn used to decide whether a component should animate a change of image.

Instead of doing this, let the user of `HUBImageLoader` (currently `HUBViewControllerImplementation`) keep track of how long time the image download took, and then - if the value exceeded a certain threshold (in the Spotify app we use `0.07` seconds, which seems to be a reasonable value). This removes the need for image loaders to perform this work, and guarantees a consistent behavior irregardless of image loader implementation.

When this is done, we can remove the `loadedFromCache` parameter in `HUBImageLoaderDelegate`.

**Comment by JohnSundell** [comment]
@Goos want to take care of this? 😄

**Comment by krris** [comment]
Hey! I will work on this.

**Comment by krris** [comment]
Implementation is done in https://github.com/spotify/HubFramework/pull/75
