### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ogezue** [spotify/HubFramework#67]
I really like the idea of HubFramework since I saw it in the App Builders conference. Are there plans to support Android as well? If I understand correctly this only works for iOS. How do you develop the Spotify Android app if you have something cool for iOS?

**Comment by JohnSundell** [comment]
@ogezue Yeah we have an Android version of the Hub Framework internally and plan to open source it too. It was just more tightly coupled with the Spotify app on Android - that's why it's taking a bit longer - so we chose to release iOS first.

**Comment by JohnSundell** [comment]
@ogezue And what's even better is that iOS & Android use the same JSON schema :)

**Comment by r00dY** [comment]
Is there a slightest chance to get any information on when we could expect Android release?

**Comment by JohnSundell** [comment]
I'll let @diegc answer this question 😉

**Comment by aminelaadhari** [comment]
Hi guys, do you still plan to open source the android version?
Thanks

**Comment by yfujiki** [comment]
I have the same question. Is there a plan?

**Comment by mcesaraccio** [comment]
@JohnSundell @diegc Hi there, any update on the Android planned release date? I am thinking about using it on both iOS and Android, using it only on one platform is not an option at the moment. 
Thanks! :)

**Comment by JohnSundell** [comment]
I don't work at Spotify anymore, so I don't have any insight into their plans 🙂 Hopefully @diegc can shed some light on this, or maybe @mhallendal or @cerihughes?

**Comment by martinkbrown** [comment]
I have the same question too :)

**Comment by zachstegall** [comment]
Same! Really getting a lot out of the iOS Framework. Is Android in the foreseeable future? Or is there a date we could expect?
