### ISSUE TITLE
Remove NSObject inheritance from all protocols.

### ISSUE THREAD

**Issue by krris** [spotify/HubFramework#70]
Currently each protocol in HubFramework looks like this:

```
@protocol HUBImageLoader <NSObject>
- (void)foo;
@end
```

IMO we can remove inheritance from `NSObject` in each protocol as far as we don't use any `NSObject` methods ([here](http://stackoverflow.com/questions/679822/why-tack-a-protocol-of-nsobject-to-a-protocol-implementation) is a discussion about this if you want to read more). What does it give us?
- Our code will be more _swifty_. 
- While writing in Swift we don't need to inherit from NSObject.
- Less code in our codebase 😉 

What do you think about this?

**Comment by JohnSundell** [comment]
I'm all for it if it doesn't have any side effects! @rastersize what do you think?

**Comment by rastersize** [comment]
AFAIK there are really only two side effects. The first is that we can’t use `@optional` to mark methods as optional in protocol. Fortunately we don’t do that 😊 Secondly we’d technically not know if our objects respond to a bunch of methods we might need, such as `-isEqual:`.

But it would be great to get rid of the conformance. Something for [2.1](https://github.com/spotify/HubFramework/milestone/1) I’d say. The tasks we need to complete to get to this state are at least:
- Audit every place where we assume an object is of type `NSObject`.
  - There are a few places where we type things as `NSObject<Something>`. This is probably not always true at the moment anyhow and will likely not be true afterwards.
- Make sure anything that _needs_, e.g., `-isEqual:` continues to conform to `NSObject` or something similar.
- Add linter making sure we don’t introduce new protocols conforming to `NSObject`.
- Add linter making sure we don’t introduce `@optional` in a protocol.
- Remove conformance of `NSObject` from our protocols.

All in all, I’m in favor of this proposal.

**Comment by JohnSundell** [comment]
Ok, let's consider this proposal passed! 👍 @krris want to proceed with the implementation?

**Comment by krris** [comment]
@JohnSundell I would love to.

**Comment by krris** [comment]
What about using http://oclint.org/ as a linter? 👍  or 👎  ?

**Comment by JohnSundell** [comment]
I'm not opposed to trying OCLint out. Seems to be widely used as well. @rastersize, @8W9aG, @cerihughes, any opinions?

**Comment by rastersize** [comment]
@krris @JohnSundell The problem we’ve encountered with linters so far is the pain of getting them configured for our code style. But if we can get that to work I’m all for linting.

**Comment by rastersize** [comment]
@krris I have not looked to much into OCLint myself, how does it compare to the [clang linter (ClangFormat)](http://clang.llvm.org/docs/ClangFormat.html)?

**Comment by JohnSundell** [comment]
Do we need to use it to lint for code style though (even though it would be super nice of course) - but maybe a first step is just to get it to lint for `NSObject` conformance + optional methods? Question is, do we even need a full blown linter for that? Simply string searching source files should do, right?

**Comment by 8W9aG** [comment]
I think if you can get it working it sounds like a good idea, I tried to get it working 2 years and failed but maybe it's evolved now

**Comment by krris** [comment]
@rastersize It's hard to compare them for me. I've never used any of them. I saw only that we use OCLint in ios-client.

**Comment by rastersize** [comment]
I took a quick 🔪 at this a few days ago. Main issue is that we need to check if objects conform to protocols (`-conformsToProtocol:`. Which is a method from the `NSObject` protocol so we cannot send the message unless conforming. Thinking about a way of working around this.

**Comment by marmelroy** [comment]
Hi @rastersize and co, I was intrigued by the discussion on this issue and played a little with an idea for solving the conformsToProtocol problem. Please see the above PR.

**Comment by rastersize** [comment]
#265 has been merged, there’s no longer any need to inherit from `NSObject` for Swift code 🐦🎉
