### ISSUE TITLE
Add API for triggering actions from content operations

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#73]
With the new `UINavigationItem` support for `HUBViewModel`, it's easy to add navigation bar items to a view in a content operation. However, since the content operation will be the one creating the buttons, we should also make it easy for it to be able to trigger actions.

**Implementation suggestion A**
Add a `HUBContentOperationActionPerformer` protocol, that gives it an `actionDelegate` that it can use to perform an action (very similar to how `HUBComponentActionPerformer` works).

**Implementation suggestion B**
Refactor `HUBComponentActionPerformerDelegate` into something more generic that both a component & content operation can use. For example `HUBActionCenter` or something (matches naming convention in `NSNotificationCenter`).

**Comment by JohnSundell** [comment]
@krris Did you make any progress on this? Otherwise do you mind if I take it over? :)

**Comment by krris** [comment]
@JohnSundell Not yet. You can take this.

**Comment by JohnSundell** [comment]
@krris Got it, thanks! 👍

**Comment by JohnSundell** [comment]
Implemented in https://github.com/spotify/HubFramework/pull/98
