### ISSUE TITLE
Send component's view to view controller's delegate instead of collection view cell

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#82]
Currently, we send the wrapping `HUBComponentCollectionViewCell` as the `view` parameter when calling methods on `HUBViewControllerDelegate`. We should change this to send the actual component view instead. 

**Current behavior:**

```objective-c
- (void)viewController:(UIViewController<HUBViewController> *)viewController
    componentWithModel:(id<HUBComponentModel>)componentModel
      willAppearInView:(UIView *)componentView
{
    // componentView is always a HUBComponentCollectionViewCell
}
```

**New behavior:**

(Imagine a component with a `UITableViewCell` as its `view`)

```objective-c
- (void)viewController:(UIViewController<HUBViewController> *)viewController
    componentWithModel:(id<HUBComponentModel>)componentModel
      willAppearInView:(UIView *)componentView
{
    // componentView is a UITableViewCell
}
```

**Comment by JohnSundell** [comment]
@krris Wanna take this on? Let me know if you need more context 🙂

**Comment by krris** [comment]
I assign it to myself. I'll get back to you with questions when I start to work on this.

**Comment by JohnSundell** [comment]
@krris Perfect 👍

**Comment by JohnSundell** [comment]
Implemented in https://github.com/spotify/HubFramework/pull/90
