### ISSUE TITLE
Extract asynchronous test utility method into a reusable method

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#93]
There's some asynchronous test code used throughout the framework, that each use manual implementations of await/expectation code. However, we already have a utility method for this in `HUBViewControllerTests`, called `performAsynchronousTestWithDelay:block:`. Extract this method into a helper category (for example) so that it can be reused in multiple places.

**Comment by sachinkesiraju** [comment]
Would you suggest creating a base test class that contains the reusable methods that all other test classes inherit from?

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
