### ISSUE TITLE
HUBViewController.visibleBodyComponentViews not working on initial load

### ISSUE THREAD

**Issue by cerihughes** [spotify/HubFramework#96]
When the `HUBViewController` first renders my data, calling `visibleBodyComponentViews` doesn't return an accurate response for the body components that are on-screen.

If I have 3 "shelves" each showing 3 child components, the index paths I get back are:
`0`, `0.2`, `1`, `1.2`, `2` and `2.2`

i.e index paths for the 1st 2 children on each "shelf" are missing.

If I scroll the shelves shelf to the end and then back again, I get the results I expect. This only happens on initial render.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
