### ISSUE TITLE
Enable components to observe actions

### ISSUE THREAD

**Issue by JohnSundell** [spotify/HubFramework#99]
Just like we now enable content operations to both **observe** and **perform** actions, we want enable components to do the same. Components are already are able to perform actions, just not observe them.

Implementation suggestion:
- Create a `HUBComponentActionObserver` protocol with a similar API to `HUBContentOperationActionObserver`.
- Notify components conforming to the that protocol whenever an action was triggered (similar to how we notifify objects conforming to `HUBContentOperationActionObserver`.

**Comment by JohnSundell** [comment]
@krris Wanna take this on?

**Comment by krris** [comment]
Implemented in https://github.com/spotify/HubFramework/pull/105
